In [2]:
from import_module import *

In [3]:
df = pd.read_csv('/mnt/NAS/youngwon/handle/nodule_bboxes.csv')
df.head()

subject  slice_location  roi_number  x_min  y_min  x_max  y_max
0  SN00000130             134           1    271    251    283    259
1  SN00000130             135           1    269    245    285    264
2  SN00000130             136           1    269    245    287    267
3  SN00000130             137           1    271    245    285    261
4  SN00000222             135           1    286    240    293    246

In [4]:
df[df['roi_number'] == 5]

subject  slice_location  roi_number  x_min  y_min  x_max  y_max
1511  SN00026194             133           5    274    229    289    241
1845  SN00030334             137           5    249    187    255    190

In [5]:
bboxes = df[['x_min','y_min','x_max','y_max']].apply(list).values
title = df[['subject','slice_location']].astype(str).values
df.columns

Index(['subject', 'slice_location', 'roi_number', 'x_min', 'y_min', 'x_max',
       'y_max'],
      dtype='object')

In [6]:
title

array([['SN00000130', '134'],
       ['SN00000130', '135'],
       ['SN00000130', '136'],
       ...,
       ['SN00040039', '134'],
       ['SN00040039', '137'],
       ['SN00040039', '138']], dtype=object)

In [7]:
df[df['roi_number']==5]

subject  slice_location  roi_number  x_min  y_min  x_max  y_max
1511  SN00026194             133           5    274    229    289    241
1845  SN00030334             137           5    249    187    255    190

In [8]:
db = {}
for a,b in zip(title,bboxes):
    key = '/'.join(a)
    if key not in db:
        db[key] = [b]
    else:
        db[key].append(b)
db['SN00030334/137']

[array([293, 213, 302, 223]),
 array([228, 193, 233, 198]),
 array([239, 200, 245, 206]),
 array([234, 215, 240, 221]),
 array([249, 187, 255, 190])]

In [17]:
root = '/mnt/NAS/youngwon/test'
a,b = getDirs(data_root=root)
for key,value in db.items():
    temp = key.split('/')
    os.makedirs('/mnt/NAS/youngwon/bboxes/{0}'.format(temp[0]),exist_ok=True)
    img_path = '{0}/{1}/{2:03d}.png'.format(root,temp[0],int(temp[1])-1)
    img = Image.open(img_path).convert('RGB')
    draw = ImageDraw.Draw(img)
    for i in range(len(value)):
        draw.rectangle((db[key][i]), outline=np.random.randint(0,255), width = 1)
    f,ax = plt.figure(figsize=(18,18)) , plt.subplot(1,1,1)
    ax.imshow(img)
    ax.axis('tight')
    plt.savefig('/mnt/NAS/youngwon/bboxes/{0}/{1}.png'.format(temp[0],temp[1]))
    plt.close()

(137, 512, 512)